'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Songs', [
      {
      "id":1,
      "youtube_link":"https://www.youtube.com/watch?v=bpOSxM0rNPM",
      "album_id":1,
      "artist_id":1,
      "name":"Do I Wanna Know",
      "length":"00:03:48",
      "track_number":1
      },
      {
      "id":2,
      "youtube_link":"https://www.youtube.com/watch?v=VQH8ZTgna3Q",
      "album_id":1,
      "artist_id":1,
      "name":"R U Mine?",
      "length":"00:03:02",
      "track_number":2
      },
      {
      "id":3,
      "youtube_link":"https://www.youtube.com/watch?v=qN7gSMPQFss",
      "album_id":1,
      "artist_id":1,
      "name":"One For The Road",
      "length":"00:04:01",
      "track_number":3
      },
      {
      "id":4,
      "youtube_link":"https://www.youtube.com/watch?v=Jn6-TItCazo",
      "album_id":1,
      "artist_id":1,
      "name":"Arabella",
      "length":"00:03:33",
      "track_number":4
      },
      {
      "id":7,
      "youtube_link":"https://www.youtube.com/watch?v=_fh64GbFSw4",
      "album_id":2,
      "artist_id":2,
      "name":"Lucid Dreams",
      "length":"00:03:27",
      "track_number":1
      },
      {
      "id":8,
      "youtube_link":"https://www.youtube.com/watch?v=Q3zpwgQK8Yg",
      "album_id":2,
      "artist_id":2,
      "name":"Wishing Well",
      "length":"00:02:57",
      "track_number":2
      },
      {
      "id":9,
      "youtube_link":"https://www.youtube.com/watch?v=TY86hAShRK4",
      "album_id":2,
      "artist_id":2,
      "name":"Righteous",
      "length":"00:03:41",
      "track_number":3
      },
      {
      "id":10,
      "youtube_link":"https://www.youtube.com/watch?v=AKJ8egrWwOY",
      "album_id":3,
      "artist_id":3,
      "name":"bellyache",
      "length":"00:03:22",
      "track_number":1
      },
      {
      "id":11,
      "youtube_link":"https://www.youtube.com/watch?v=9dobJDxPEzM",
      "album_id":3,
      "artist_id":3,
      "name":"watch",
      "length":"00:03:56",
      "track_number":2
      },
      {
      "id":12,
      "youtube_link":"https://www.youtube.com/watch?v=dVUmSgzgOqs",
      "album_id":3,
      "artist_id":3,
      "name":"my boy",
      "length":"00:03:12",
      "track_number":3
      },
      {
      "id":13,
      "youtube_link":"https://www.youtube.com/watch?v=Msl2fl3h59I",
      "album_id":4,
      "artist_id":4,
      "name":"Count on me",
      "length":"00:04:50",
      "track_number":1
      },
      {
      "id":14,
      "youtube_link":"https://www.youtube.com/watch?v=SR6iYWJxHqs",
      "album_id":4,
      "artist_id":4,
      "name":"Grenade",
      "length":"00:03:31",
      "track_number":2
      },
      {
      "id":15,
      "youtube_link":"https://www.youtube.com/watch?v=WeTV9ad1sP0",
      "album_id":4,
      "artist_id":4,
      "name":"That's What I Like",
      "length":"00:05:01",
      "track_number":3
      },
      {
      "id":16,
      "youtube_link":"https://www.youtube.com/watch?v=1bGI3fwz40c",
      "album_id":5,
      "artist_id":5,
      "name":"Aura",
      "length":"00:03:41",
      "track_number":1
      },
      {
      "id":17,
      "youtube_link":"https://www.youtube.com/watch?v=whbidPR4nVA",
      "album_id":5,
      "artist_id":5,
      "name":"Alien",
      "length":"00:02:41",
      "track_number":2
      },
      {
      "id":18,
      "youtube_link":"https://www.youtube.com/watch?v=COz9lDCFHjw",
      "album_id":6,
      "artist_id":6,
      "name":"Passionfruit",
      "length":"00:04:11",
      "track_number":1
      },
      {
      "id":19,
      "youtube_link":"https://www.youtube.com/watch?v=0GIWWFdOw_0",
      "album_id":6,
      "artist_id":6,
      "name":"Blem",
      "length":"00:03:51",
      "track_number":2
      },
      {
      "id":20,
      "youtube_link":"https://www.youtube.com/watch?v=iAbnEUA0wpA",
      "album_id":6,
      "artist_id":6,
      "name":"One Dance",
      "length":"00:03:23",
      "track_number":3
      },
      {
      "id":21,
      "youtube_link":"https://www.youtube.com/watch?v=2F2GlWMb_l4",
      "album_id":6,
      "artist_id":6,
      "name":"Childs Play",
      "length":"00:04:29",
      "track_number":4
      },
      {
      "id":22,
      "youtube_link":"https://www.youtube.com/watch?v=HHWcnaJXeIY",
      "album_id":7,
      "artist_id":7,
      "name":"Eize Yom",
      "length":"00:03:54",
      "track_number":1
      },
      {
      "id":23,
      "youtube_link":"https://www.youtube.com/watch?v=NyxnG-pSO5M",
      "album_id":7,
      "artist_id":7,
      "name":"Mishtara",
      "length":"00:03:12",
      "track_number":2
      },
      {
      "id":24,
      "youtube_link":"https://www.youtube.com/watch?v=QGErHQi1tuc",
      "album_id":7,
      "artist_id":7,
      "name":"Lola",
      "length":"00:03:32",
      "track_number":3
      },
      {
      "id":25,
      "youtube_link":"https://www.youtube.com/watch?v=pse5JzwHVtM",
      "album_id":8,
      "artist_id":8,
      "name":"Shemisheu yaatzor oti",
      "length":"00:03:23",
      "track_number":1
      },
      {
      "id":26,
      "youtube_link":"https://www.youtube.com/watch?v=pzAmYC7Xxtw",
      "album_id":8,
      "artist_id":8,
      "name":"Kapiot",
      "length":"00:04:03",
      "track_number":2
      },
      {
      "id":27,
      "youtube_link":"https://www.youtube.com/watch?v=pgAPwe4Ze3I",
      "album_id":8,
      "artist_id":8,
      "name":"Shikorim",
      "length":"00:03:37",
      "track_number":3
      },
      {
      "id":28,
      "youtube_link":"https://www.youtube.com/watch?v=9u6KzOF9N2Y",
      "album_id":9,
      "artist_id":9,
      "name":"3am",
      "length":"00:03:25",
      "track_number":1
      },
      {
      "id":29,
      "youtube_link":"https://www.youtube.com/watch?v=rPgaYeq9NvI",
      "album_id":9,
      "artist_id":9,
      "name":"Graveyard",
      "length":"00:03:39",
      "track_number":2
      },
      {
      "id":30,
      "youtube_link":"https://www.youtube.com/watch?v=2GNYSWeCwDg",
      "album_id":9,
      "artist_id":9,
      "name":"Ashley",
      "length":"00:03:15",
      "track_number":3
      },
      {
      "id":31,
      "youtube_link":"https://www.youtube.com/watch?v=4xm66KOZ7EE",
      "album_id":10,
      "artist_id":10,
      "name":"En Otach",
      "length":"00:03:17",
      "track_number":1
      },
      {
      "id":32,
      "youtube_link":"https://www.youtube.com/watch?v=kDs-qWUO5BM",
      "album_id":10,
      "artist_id":10,
      "name":"Ad Sheyaale Hayom Aba",
      "length":"00:03:36",
      "track_number":2
      },
      {
      "id":33,
      "youtube_link":"https://www.youtube.com/watch?v=ykcuk4tnzuk",
      "album_id":10,
      "artist_id":10,
      "name":"Menasim",
      "length":"00:03:11",
      "track_number":3
      },
      {
      "id":34,
      "youtube_link":"https://www.youtube.com/watch?v=-qxrnxoHl6A",
      "album_id":11,
      "artist_id":11,
      "name":"Hinech Yafa",
      "length":"00:04:13",
      "track_number":1
      },
      {
      "id":35,
      "youtube_link":"https://www.youtube.com/watch?v=kmW2yAYhMmM",
      "album_id":11,
      "artist_id":11,
      "name":"Mimamakim",
      "length":"00:03:20",
      "track_number":2
      },
      {
      "id":36,
      "youtube_link":"https://www.youtube.com/watch?v=cXQ6uVJtH_Q",
      "album_id":11,
      "artist_id":11,
      "name":"Im Telech",
      "length":"00:04:43",
      "track_number":3
      },
      {
      "id":37,
      "youtube_link":"https://www.youtube.com/watch?v=egtOB8arAN0",
      "album_id":11,
      "artist_id":11,
      "name":"Shoshanim Atzovot",
      "length":"00:03:33",
      "track_number":4
      },
      {
      "id":38,
      "youtube_link":"https://www.youtube.com/watch?v=0-7IHOXkiV8",
      "album_id":12,
      "artist_id":12,
      "name":"Way Down We Go",
      "length":"00:03:50",
      "track_number":1
      },
      {
      "id":39,
      "youtube_link":"https://www.youtube.com/watch?v=jfNOdsvMke4",
      "album_id":12,
      "artist_id":12,
      "name":"I Cant Go On Without You",
      "length":"00:03:48",
      "track_number":2
      },
      {
      "id":40,
      "youtube_link":"https://www.youtube.com/watch?v=FNwgOkl5nRY",
      "album_id":12,
      "artist_id":12,
      "name":"All The Pretty Girls",
      "length":"00:03:43",
      "track_number":3
      },
      {
      "id":41,
      "youtube_link":"https://www.youtube.com/watch?v=iI2f8eA8x4Q",
      "album_id":13,
      "artist_id":13,
      "name":"Suncity",
      "length":"00:03:23",
      "track_number":1
      },
      {
      "id":42,
      "youtube_link":"https://www.youtube.com/watch?v=x3bfa3DZ8JM",
      "album_id":13,
      "artist_id":13,
      "name":"Better",
      "length":"00:03:32",
      "track_number":2
      },
      {
      "id":43,
      "youtube_link":"https://www.youtube.com/watch?v=rbHIDVVTSNA",
      "album_id":13,
      "artist_id":13,
      "name":"Right Back",
      "length":"00:04:03",
      "track_number":3
      },
      {
      "id":44,
      "youtube_link":"https://www.youtube.com/watch?v=c9JeSLcdbGg",
      "album_id":14,
      "artist_id":14,
      "name":"Yesh Yamim",
      "length":"00:03:33",
      "track_number":1
      },
      {
      "id":45,
      "youtube_link":"https://www.youtube.com/watch?v=pvW-R5XcJJA",
      "album_id":14,
      "artist_id":14,
      "name":"Achat Kamoni",
      "length":"00:02:53",
      "track_number":2
      },
      {
      "id":46,
      "youtube_link":"https://www.youtube.com/watch?v=2LyG5dW4EFA",
      "album_id":14,
      "artist_id":14,
      "name":"Boei",
      "length":"00:03:35",
      "track_number":3
      },
      {
      "id":47,
      "youtube_link":"https://www.youtube.com/watch?v=Y7ix6RITXM0",
      "album_id":15,
      "artist_id":15,
      "name":"Maps",
      "length":"00:03:27",
      "track_number":1
      },
      {
      "id":48,
      "youtube_link":"https://www.youtube.com/watch?v=XPpTgCho5ZA",
      "album_id":15,
      "artist_id":15,
      "name":"This Love",
      "length":"00:03:39",
      "track_number":2
      },
      {
      "id":49,
      "youtube_link":"https://www.youtube.com/watch?v=dkQ0OJ5Byls",
      "album_id":15,
      "artist_id":15,
      "name":"Wake Up Call",
      "length":"00:03:49",
      "track_number":3
      },
      {
      "id":50,
      "youtube_link":"https://www.youtube.com/watch?v=A60S_Fkd2XY",
      "album_id":16,
      "artist_id":16,
      "name":"Stolen Dance",
      "length":"00:05:14",
      "track_number":1
      },
      {
      "id":51,
      "youtube_link":"https://www.youtube.com/watch?v=4XHmlWT-XqU",
      "album_id":16,
      "artist_id":16,
      "name":"We Didnt Make It To The Moon",
      "length":"00:03:53",
      "track_number":2
      },
      {
      "id":52,
      "youtube_link":"https://www.youtube.com/watch?v=ernVvrYH9vg",
      "album_id":16,
      "artist_id":16,
      "name":"Cocoon",
      "length":"00:02:43",
      "track_number":3
      },
      {
      "id":53,
      "youtube_link":"https://www.youtube.com/watch?v=Zx_DBvChpvM",
      "album_id":17,
      "artist_id":17,
      "name":"Wolves",
      "length":"00:03:37",
      "track_number":1
      },
      {
      "id":54,
      "youtube_link":"https://www.youtube.com/watch?v=au2n7VVGv_c",
      "album_id":17,
      "artist_id":17,
      "name":"Psycho",
      "length":"00:03:40",
      "track_number":2
      },
      {
      "id":55,
      "youtube_link":"https://www.youtube.com/watch?v=UceaB4D0jpo",
      "album_id":17,
      "artist_id":17,
      "name":"Rockstar",
      "length":"00:03:41",
      "track_number":3
      },
      {
      "id":56,
      "youtube_link":"https://www.youtube.com/watch?v=rn_YodiJO6k",
      "album_id":18,
      "artist_id":18,
      "name":"Otherside",
      "length":"00:04:47",
      "track_number":1
      },
      {
      "id":57,
      "youtube_link":"https://www.youtube.com/watch?v=YlUKcNNmywk",
      "album_id":18,
      "artist_id":18,
      "name":"Californication",
      "length":"00:05:13",
      "track_number":2
      },
      {
      "id":58,
      "youtube_link":"https://www.youtube.com/watch?v=6ONRf7h3Mdk",
      "album_id":19,
      "artist_id":19,
      "name":"SICKO MODE",
      "length":"00:04:53",
      "track_number":1
      },
      {
      "id":59,
      "youtube_link":"https://www.youtube.com/watch?v=2a8PgqWrc_4",
      "album_id":19,
      "artist_id":19,
      "name":"STARGAZING",
      "length":"00:03:45",
      "track_number":2
      },
      {
      "id":60,
      "youtube_link":"https://www.youtube.com/watch?v=FAO8ZAUBx0c",
      "album_id":19,
      "artist_id":19,
      "name":"WAKE UP",
      "length":"00:03:51",
      "track_number":3
      },
      {
      "id":61,
      "youtube_link":"https://www.youtube.com/watch?v=TUj0otkJEBo",
      "album_id":20,
      "artist_id":20,
      "name":"Or Nah",
      "length":"00:04:26",
      "track_number":1
      },
      {
      "id":62,
      "youtube_link":"https://www.youtube.com/watch?v=JZjAg6fK-BQ",
      "album_id":20,
      "artist_id":20,
      "name":"Reminder",
      "length":"00:03:18",
      "track_number":2
      },
      {
      "id":63,
      "youtube_link":"https://www.youtube.com/watch?v=9CbQl98JEbE",
      "album_id":20,
      "artist_id":20,
      "name":"In The Night",
      "length":"00:03:28",
      "track_number":3
      },
      {
      "id":64,
      "youtube_link":"https://www.youtube.com/watch?v=KEI4qSrkPAs",
      "album_id":20,
      "artist_id":20,
      "name":"Cant Feel My Face",
      "length":"00:04:03",
      "track_number":4
      },
      {
      "id":65,
      "youtube_link":"https://www.youtube.com/watch?v=SA7AIQw-7Ms",
      "album_id":9,
      "artist_id":9,
      "name":"Him & I",
      "length":"00:04:08",
      "track_number":4
      },
      {
      "id":66,
      "youtube_link":"https://www.youtube.com/watch?v=R7A1mIdiheE",
      "album_id":1,
      "artist_id":1,
      "name":"Knee Socks",
      "length":"00:03:22",
      "track_number":5
      },
      {
      "id":67,
      "youtube_link":"https://www.youtube.com/watch?v=CIqiB9zSLmM",
      "album_id":5,
      "artist_id":5,
      "name":"GFY",
      "length":"00:03:45",
      "track_number":3
      },
      {
      "id":68,
      "youtube_link":"https://www.youtube.com/watch?v=Q0oIoR9mLwc",
      "album_id":18,
      "artist_id":18,
      "name":"Dark Necessities",
      "length":"00:05:02",
      "track_number":3
      },
      {
      "id":69,
      "youtube_link":"https://www.youtube.com/watch?v=8DyziWtkfBw",
      "album_id":18,
      "artist_id":18,
      "name":"Can't Stop",
      "length":"00:04:44",
      "track_number":4
      },
      {
      "id":70,
      "youtube_link":"https://www.youtube.com/watch?v=Dst9gZkq1a8",
      "album_id":19,
      "artist_id":19,
      "name":"goosebumps",
      "length":"00:03:58",
      "track_number":4
      },
      {
      "id":71,
      "youtube_link":"https://www.youtube.com/watch?v=wXhTHyIgQ_U",
      "album_id":17,
      "artist_id":17,
      "name":"Circles",
      "length":"00:03:58",
      "track_number":4
      },
      {
      "id":72,
      "youtube_link":"https://www.youtube.com/watch?v=qlGQoxzdwP4",
      "album_id":16,
      "artist_id":16,
      "name":"Down By The River",
      "length":"00:04:33",
      "track_number":4
      },
      {
      "id":73,
      "youtube_link":"https://www.youtube.com/watch?v=2fX81jBEH84",
      "album_id":2,
      "artist_id":2,
      "name":"Bandit",
      "length":"00:03:54",
      "track_number":4
      },
      {
      "id":74,
      "youtube_link":"https://www.youtube.com/watch?v=IiIDghGyy7Y",
      "album_id":3,
      "artist_id":3,
      "name":"my strange addiction",
      "length":"00:03:23",
      "track_number":4
      },
      {
      "id":75,
      "youtube_link":"https://www.youtube.com/watch?v=fLexgOxsZu0",
      "album_id":4,
      "artist_id":4,
      "name":"The Lazy Song",
      "length":"00:03:45",
      "track_number":4
      },
      {
      "id":76,
      "youtube_link":"https://www.youtube.com/watch?v=kCfVv3RsGw4",
      "album_id":5,
      "artist_id":5,
      "name":"Nevermind",
      "length":"00:02:53",
      "track_number":4
      },
      {
      "id":77,
      "youtube_link":"https://www.youtube.com/watch?v=wN0LFlMvvsw",
      "album_id":7,
      "artist_id":7,
      "name":"Ani Ratz",
      "length":"00:02:58",
      "track_number":4
      },
      {
      "id":78,
      "youtube_link":"https://www.youtube.com/watch?v=hySvIlHhCgA",
      "album_id":8,
      "artist_id":8,
      "name":"En Yoter Moadonim",
      "length":"00:03:12",
      "track_number":4
      },
      {
      "id":79,
      "youtube_link":"https://www.youtube.com/watch?v=x7wrPEatuk4",
      "album_id":10,
      "artist_id":10,
      "name":"Nigmar",
      "length":"00:04:10",
      "track_number":4
      },
      {
      "id":80,
      "youtube_link":"https://www.youtube.com/watch?v=Da5qQD_RpEQ",
      "album_id":12,
      "artist_id":12,
      "name":"Vor í Vaglaskógi",
      "length":"00:04:24",
      "track_number":4
      },
      {
      "id":81,
      "youtube_link":"https://www.youtube.com/watch?v=IPfJnp1guPc",
      "album_id":13,
      "artist_id":13,
      "name":"Young Dumb & Broke",
      "length":"00:04:07",
      "track_number":4
      },
      {
      "id":82,
      "youtube_link":"https://www.youtube.com/watch?v=_cubmeyBlGA",
      "album_id":14,
      "artist_id":14,
      "name":"Lalechet",
      "length":"00:03:08",
      "track_number":4
      },
      {
      "id":83,
      "youtube_link":"https://www.youtube.com/watch?v=cffui_Os9RE",
      "album_id":15,
      "artist_id":15,
      "name":"Misery",
      "length":"00:03:34",
      "track_number":4
      }
      ], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
